name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Run linting
        run: npm run lint
      
      - name: Run tests
        run: npm test
      
      - name: Build application
        run: npm run build
      
      - name: List build directory contents
        run: ls -la dist || ls -la build || echo "No dist or build directory found"
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: |
            dist/
            build/
          if-no-files-found: warn
  
  docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Construimos de nuevo en lugar de depender del artefacto
      - name: Setup Node.js and build for Docker
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install and build
        run: npm ci --legacy-peer-deps && npm run build
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: hospital-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Test Docker container
        run: |
          docker run --name hospital-app-test -d -p 8080:80 hospital-app:latest
          sleep 5
          # Usar una comprobaci칩n m치s b치sica que no falle si la p치gina no responde inmediatamente
          docker ps | grep hospital-app-test
          docker stop hospital-app-test