name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-test-and-docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Run linting
        run: npm run lint
        continue-on-error: true
      
      - name: Run tests
        run: npm test
        continue-on-error: true
      
      - name: Build application
        run: npm run build
      
      - name: List build directory contents
        run: ls -la dist || ls -la build || echo "No dist or build directory found"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: hospital-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Test Docker container
        run: |
          docker run --name hospital-app-test -d -p 8080:80 hospital-app:latest
          sleep 5
          docker ps | grep hospital-app-test
          docker stop hospital-app-test || true